language: python
python:
  - "3.4"
# command to install dependencies
install:
- "sudo apt-get update"
- "sudo apt-get install graphviz"
- "pip install -r requirements.txt"
# command to run tests
script:
- "python manage.py makemigrations"
- "python manage.py migrate"
- "python manage.py test"